dist: trusty
language: node_js
node_js:
- "stable"
before_script:
- npm install
script:
- npm run build
deploy:
  provider: surge
  project: ./build/
  domain: kontent-sample-app-react.surge.sh 
  skip_cleanup: true

